# Generated by Django 6.0 on 2025-12-20 16:48

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_suitability_score', models.FloatField()),
                ('overall_risk_tier', models.CharField(max_length=20)),
                ('last_analyzed_at', models.DateTimeField(auto_now=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='safety_checker.youtubechannel')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='safety_checker.youtubechannel')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(help_text='0.0 (Unsafe) to 1.0 (Safe)')),
                ('risk_tier', models.CharField(choices=[('SAFE', 'Brand Safe'), ('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='HIGH', max_length=20)),
                ('is_brand_safe', models.BooleanField(default=False)),
                ('garm_scores', models.JSONField(default=dict, help_text='Detailed scores per GARM category')),
                ('detected_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('analysis_summary', models.TextField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processor_version', models.CharField(default='v1.0', max_length=50)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='safety_checker.youtubevideo')),
            ],
        ),
    ]
